export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  // page.tsx ma jo component bany ga wo is child prop se replace ho jay ga.
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1>this is the navbar</h1>
        {children}
        <footer>this is the footer</footer>
      </body>
    </html>
  );
}
