export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  // page.tsx ma jo component bany ga wo is child prop se replace ho jay ga.
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <p>this is the navbar</p>
      <body>{children}</body>
      <footer>this is the footer</footer>
    </html>
  );
}
